name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SHOPIFY_DOMAIN: "${{ secrets.SHOPIFY_DOMAIN }}"
      SHOPIFY_TOKEN: "${{ secrets.SHOPIFY_TOKEN }}"
      BULK_SUCCESS_ID: "${{ secrets.BULK_SUCCESS_ID }}"
      BULK_FAILED_ID_ERRORS: "${{ secrets.BULK_FAILED_ID_ERRORS }}"
      BULK_FAILED_ID_USER_ERRORS: "${{ secrets.BULK_FAILED_ID_USER_ERRORS }}"
      BULK_CANCELED_ID: "${{ secrets.BULK_CANCELED_ID }}"
      BULK_PARTIAL_ID: "${{ secrets.BULK_PARTIAL_ID }}"

    strategy:
      matrix:
        ruby: ['4', '3.4', '3.3', '3.2', '3.1', '3.0', '2.7']

    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
          bundler: '2.4.22'

      - run: bundle install
      - run: bundle exec rake
